export const INPUTS_VALUE = [
  {
    id: Date.now() + Math.random(),
    marks: [],
    markString: '',
    type: 'Локальная',
    login: '',
    password: '',
    errors: {},
  },
  {
    id: Date.now() + Math.random(),
    marks: [],
    markString: '',
    type: 'Локальная',
    login: '',
    password: '',
    errors: {},
  },
  {
    id: Date.now() + Math.random(),
    marks: [],
    markString: '',
    type: 'Локальная',
    login: '',
    password: '',
    errors: {},
  },
  {
    id: Date.now() + Math.random(),
    marks: [],
    markString: '',
    type: 'Локальная',
    login: '',
    password: '',
    errors: {},
  },
]
